---

## As continuous integration server, containers can stack and fill the disk... regular spring cleaning needed
##  Attention, this will remove all running containers as we suppose server is dedicated to jenkins

- name: add scripts for cleaning
  template: "src={{ item }}.j2 dest=/usr/local/bin/{{ item }} mode=0755"
  with_items:
    - docker-cleaning.sh
    - lxc-cleaning.sh
- name: cron task to clean docker ps + images
  cron: name="docker cleaning" minute="15" hour="5" job="/usr/local/bin/docker-cleaning.sh"
- name: cron task to clean lxc running images
  cron: name="lxc cleaning" minute="35" hour="5" job="/usr/local/bin/lxc-cleaning.sh"

