---

- name: apt | jenkins dependencies
  apt: name={{item}} state=present
  with_items:
    - git
    - subversion
    - graphviz
    - ufw

- name: apt | jenkins dependencies - extra
  apt: name={{item}} state=present
  with_items:
    - "{{ jenkinsenv_extra_pkg }}"

