---

- name: apt | jenkins dependencies
  apt:
    name: ['git', 'subversion', 'graphviz', 'ufw']
    state: present
  register: pkg_result
  until: pkg_result is success

- name: apt | jenkins dependencies - extra
  apt: name={{ jenkinsenv_extra_pkg }} state=present
  register: pkg_result
  until: pkg_result is success
