---
## Tools for PHP Testing
## composer tools are in /usr/share/composer/vendor/bin

- include: composer.yml

- name: install phpunit testing tools - version choice
  get_url: "url={{ item.u }} dest=/usr/local/bin/{{ item.d }} mode=0755 sha256sum={{ item.s }}"
  with_items:
    - { u: 'https://github.com/phpmetrics/PhpMetrics/raw/v1.10.0/build/phpmetrics.phar', d: 'phpmetrics', s: 'a7aac1115f6ad30365d89655744bb2a3bfed6e798ad30e37ddefd1fa0618da57' }

## Phpunit 4.8, only choice if php < 5.6
- name: install phpunit testing tool - 4.8
  get_url: "url={{ item.u }} dest=/usr/local/bin/{{ item.d }} mode={{ item.m }}"
  with_items:
## Phpunit (current)
## https://phpunit.de/manual/current/en/installation.html#installation.phar.verification
    - { u: 'https://phar.phpunit.de/phpunit-4.8.phar', d: 'phpunit48', m: '0755' }
    - { u: 'https://phar.phpunit.de/phpunit-4.8.phar.asc', d: 'phpunit48.asc', m: '0644' }
- name: recover phpunit gpg key
  command: "gpg --keyserver pgp.uni-mainz.de --recv-keys 0x4AA394086372C20A"
  register: import
  changed_when: "'imported: 1' in import.stdout"

- name: gpg verify current phpunit download
  command: "gpg --verify /usr/local/bin/phpunit48.asc"
  register: gpgresult
  changed_when: false
  failed_when: gpgresult.rc != 0

- name: install phpunit testing tool - currrent
  get_url: "url={{ item.u }} dest=/usr/local/bin/{{ item.d }} mode={{ item.m }}"
  with_items:
## Phpunit (current)
## https://phpunit.de/manual/current/en/installation.html#installation.phar.verification
    - { u: 'https://phar.phpunit.de/phpunit.phar', d: 'phpunit', m: '0755' }
    - { u: 'https://phar.phpunit.de/phpunit.phar.asc', d: 'phpunit.asc', m: '0644' }
- name: recover phpunit gpg key
  command: "gpg --keyserver pgp.uni-mainz.de --recv-keys 0x4AA394086372C20A"
  register: import
  changed_when: "'imported: 1' in import.stdout"

- name: gpg verify current phpunit download
  command: "gpg --verify /usr/local/bin/phpunit.asc"
  register: gpgresult
  changed_when: false
  failed_when: gpgresult.rc != 0

