---
## Tools for PHP Testing
## composer tools are in /usr/share/composer/vendor/bin

- include: composer.yml

- name: install phpunit testing tools - version choice
  get_url: "url={{ item.u }} dest=/usr/local/bin/{{ item.d }} mode=0755 sha256sum={{ item.s }}"
  with_items:
## Phpunit 4.8, only choice if php < 5.6
    - { u: 'https://phar.phpunit.de/phpunit-old.phar', d: 'phpunit48', s: '4fd145a62bd3358349cbb190da4532a00219b8fa637ff51485931fa54ff04864' }
    - { u: 'https://github.com/phpmetrics/PhpMetrics/raw/master/build/phpmetrics.phar', d: 'phpmetrics', s: 'c2a91d6e8269286e7eab33a649293cfbaefdeb965088620930ca2d788c921ce6' }

- name: install phpunit testing tool - currrent
  get_url: "url={{ item.u }} dest=/usr/local/bin/{{ item.d }} mode={{ item.m }}"
  with_items:
## Phpunit (current)
## https://phpunit.de/manual/current/en/installation.html#installation.phar.verification
    - { u: 'https://phar.phpunit.de/phpunit.phar', d: 'phpunit', m: '0755' }
    - { u: 'https://phar.phpunit.de/phpunit.phar.asc', d: 'phpunit.asc', m: '0644' }
- name: recover phpunit gpg key
  command: "gpg --keyserver pgp.uni-mainz.de --recv-keys 0x4AA394086372C20A"
  register: import
  changed_when: "'imported: 1' in import.stdout"

- name: gpg verify current phpunit download
  command: "gpg --verify /usr/local/bin/phpunit.asc"
  register: gpgresult
  changed_when: false
  failed_when: gpgresult.rc != 0

