---

- include_vars: "{{ansible_distribution}}.{{ansible_lsb.major_release|int}}.yml"

- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

## testing tools? slave?
- include: jenkins-test-php.yml
- include: jenkins-test-ansible.yml

